CREATE DATABASE HOTELDB;

\c HOTELDB;

CREATE TABLE QUARTO(
	ID_QUARTO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NUMERO_QUARTO VARCHAR(255) NOT NULL,
	ANDAR INTEGER NOT NULL,
	TIPO VARCHAR(100) NOT NULL,
	STATUS_OCUPACAO BOOLEAN DEFAULT FALSE,
	STATUS_INVENTARIO VARCHAR(255),
	DATA_ULTIMA_RESERVA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DATA_DISPONIBILIDADE_RESERVA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
); 

CREATE TABLE HOSPEDE(
	ID_HOSPEDE BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	CODIGO_HOSPEDE INTEGER NOT NULL,
	NOME_COMPLETO VARCHAR(255) NOT NULL,
	DOCUMENTO VARCHAR(100) NOT NULL,
	HOSPEDADO BOOLEAN NOT NULL DEFAULT FALSE,
	DATA_ULTIMA_HOSPEDAGEM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DATA_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RESERVA_QUARTO(
	ID_RESERVA_QUARTO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ID_QUARTO INTEGER REFERENCES QUARTO(ID_QUARTO),
	ID_HOSPEDE INTEGER REFERENCES HOSPEDE(ID_HOSPEDE),
	NUMERO_RESERVA INTEGER NOT NULL,
	DATA_INICIO_RESERVA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DATA_FIM_RESERVA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DATA_MAXIMA_CANCELAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO QUARTO (NUMERO_QUARTO, ANDAR, TIPO, STATUS_OCUPACAO, STATUS_INVENTARIO)
VALUES ('100', 1, 'Padrão', FALSE, 'OK');

INSERT INTO QUARTO (NUMERO_QUARTO, ANDAR, TIPO, STATUS_OCUPACAO, STATUS_INVENTARIO)
VALUES ('101', 1, 'Alto padrão', FALSE, 'OK');

INSERT INTO QUARTO (NUMERO_QUARTO, ANDAR, TIPO, STATUS_OCUPACAO, STATUS_INVENTARIO)
VALUES ('200', 12, 'Luxo', FALSE, 'OK');

INSERT INTO QUARTO (NUMERO_QUARTO, ANDAR, TIPO, STATUS_OCUPACAO, STATUS_INVENTARIO)
VALUES ('201', 2, 'Econônico', FALSE, 'OK');

INSERT INTO HOSPEDE (CODIGO_HOSPEDE, NOME_COMPLETO, DOCUMENTO)
VALUES (1001, 'Carlos Silva', 'RG12345678');

INSERT INTO HOSPEDE (CODIGO_HOSPEDE, NOME_COMPLETO, DOCUMENTO)
VALUES (1002, 'Maria Oliveira', 'CPF987654321');

INSERT INTO HOSPEDE (CODIGO_HOSPEDE, NOME_COMPLETO, DOCUMENTO, DATA_ULTIMA_HOSPEDAGEM)
VALUES (1003, 'João Souza', 'RG87654321', '2025-09-15 18:30:00');

INSERT INTO HOSPEDE (CODIGO_HOSPEDE, NOME_COMPLETO, DOCUMENTO)
VALUES (1004, 'Fernando Lima', 'RG44556677');





