CREATE DATABASE HOTELDB;

\c HOTELDB;

CREATE TABLE QUARTO(
	ID_QUARTO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NUMERO_QUARTO VARCHAR(255) NOT NULL,
	ANDAR INTEGER NOT NULL,
	TIPO VARCHAR(100) NOT NULL,
	STATUS_OCUPACAO BOOLEAN DEFAULT FALSE,
	STATUS_INVENTARIO VARCHAR(255),
	DATA_ULTIMA_RESERVA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DATA_DISPONIBILIDADE_RESERVA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
); 

CREATE TABLE HOSPEDE(
	ID_HOSPEDE BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	CODIGO_HOSPEDE BIGINT GENERATED ALWAYS AS IDENTITY,
	NOME_COMPLETO VARCHAR(255) NOT NULL,
	DOCUMENTO VARCHAR(100) NOT NULL,
	HOSPEDADO BOOLEAN NOT NULL DEFAULT FALSE,
	DATA_ULTIMA_HOSPEDAGEM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DATA_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RESERVA_QUARTO(
	ID_RESERVA_QUARTO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ID_QUARTO INTEGER REFERENCES QUARTO(ID_QUARTO),
	ID_HOSPEDE INTEGER REFERENCES HOSPEDE(ID_HOSPEDE),
	NUMERO_RESERVA BIGINT GENERATED ALWAYS AS IDENTITY,
	DATA_INICIO_RESERVA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DATA_FIM_RESERVA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DATA_MAXIMA_CANCELAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO QUARTO (NUMERO_QUARTO, ANDAR, TIPO, STATUS_OCUPACAO, STATUS_INVENTARIO, DATA_DISPONIBILIDADE_RESERVA)
VALUES ('100', 1, 'Padrão', FALSE, 'OK','2025-09-01 12:00:00');

INSERT INTO QUARTO (NUMERO_QUARTO, ANDAR, TIPO, STATUS_OCUPACAO, STATUS_INVENTARIO, DATA_DISPONIBILIDADE_RESERVA)
VALUES ('101', 1, 'Alto padrão', FALSE, 'OK','2025-09-01 12:00:00');

INSERT INTO QUARTO (NUMERO_QUARTO, ANDAR, TIPO, STATUS_OCUPACAO, STATUS_INVENTARIO, DATA_DISPONIBILIDADE_RESERVA)
VALUES ('200', 12, 'Luxo', FALSE, 'OK','2025-09-01 12:00:00');

INSERT INTO QUARTO (NUMERO_QUARTO, ANDAR, TIPO, STATUS_OCUPACAO, STATUS_INVENTARIO, DATA_DISPONIBILIDADE_RESERVA)
VALUES ('201', 2, 'Econômico', FALSE, 'OK','2025-09-01 12:00:00');

INSERT INTO HOSPEDE (NOME_COMPLETO, DOCUMENTO)
VALUES ('Carlos Silva', 'RG12345678');

INSERT INTO HOSPEDE (NOME_COMPLETO, DOCUMENTO)
VALUES ('Maria Oliveira', 'CPF987654321');

INSERT INTO HOSPEDE (NOME_COMPLETO, DOCUMENTO)
VALUES ('João Souza', 'RG87654321');

INSERT INTO HOSPEDE (NOME_COMPLETO, DOCUMENTO)
VALUES ('Fernando Lima', 'RG44556677');

